// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LoginDto = {
    /**
     * User email address
     */
    email: string;
    /**
     * User password
     */
    password: string;
};

export type AuthResponseDto = {
    id: string;
    email: string;
    name: string;
    role: 'admin' | 'manager' | 'agent';
    tenantId: string;
    tenantName: string;
    status: 'active' | 'inactive' | 'suspended';
};

export type ProblemDetailsDto = {
    type: string;
    title: string;
    status: number;
    code: string;
    detail: string;
    instance: string;
    i18nKey?: string;
    fieldErrors?: {
        [key: string]: unknown;
    };
};

export type LogoutResponseDto = {
    success: boolean;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Validation error
     */
    400: ProblemDetailsDto;
    /**
     * Invalid credentials
     */
    401: ProblemDetailsDto;
};

export type AuthControllerLoginError = AuthControllerLoginErrors[keyof AuthControllerLoginErrors];

export type AuthControllerLoginResponses = {
    /**
     * Login successful
     */
    200: AuthResponseDto;
};

export type AuthControllerLoginResponse = AuthControllerLoginResponses[keyof AuthControllerLoginResponses];

export type AuthControllerRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type AuthControllerRefreshErrors = {
    /**
     * Token expired or invalid
     */
    401: ProblemDetailsDto;
};

export type AuthControllerRefreshError = AuthControllerRefreshErrors[keyof AuthControllerRefreshErrors];

export type AuthControllerRefreshResponses = {
    /**
     * Token refreshed
     */
    200: AuthResponseDto;
};

export type AuthControllerRefreshResponse = AuthControllerRefreshResponses[keyof AuthControllerRefreshResponses];

export type AuthControllerLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type AuthControllerLogoutErrors = {
    /**
     * Not authenticated
     */
    401: ProblemDetailsDto;
};

export type AuthControllerLogoutError = AuthControllerLogoutErrors[keyof AuthControllerLogoutErrors];

export type AuthControllerLogoutResponses = {
    /**
     * Logout successful
     */
    200: LogoutResponseDto;
};

export type AuthControllerLogoutResponse = AuthControllerLogoutResponses[keyof AuthControllerLogoutResponses];

export type AuthControllerMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type AuthControllerMeErrors = {
    /**
     * Not authenticated
     */
    401: ProblemDetailsDto;
};

export type AuthControllerMeError = AuthControllerMeErrors[keyof AuthControllerMeErrors];

export type AuthControllerMeResponses = {
    /**
     * Current user
     */
    200: AuthResponseDto;
};

export type AuthControllerMeResponse = AuthControllerMeResponses[keyof AuthControllerMeResponses];
