/**
 * Machine-readable error codes used across the API.
 * These form the contract between frontend and backend per ADR-0008.
 */
export const ErrorCodes = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Tenant / Organization
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  SLUG_EXISTS: 'SLUG_EXISTS',
  EMAIL_EXISTS: 'EMAIL_EXISTS',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_ROLE_INVALID: 'USER_ROLE_INVALID',
  LAST_ADMIN: 'LAST_ADMIN',
  CANNOT_DEACTIVATE_SELF: 'CANNOT_DEACTIVATE_SELF',
  ALREADY_INACTIVE: 'ALREADY_INACTIVE',

  // Lead
  LEAD_NOT_FOUND: 'LEAD_NOT_FOUND',
  LEAD_STAGE_INVALID: 'LEAD_STAGE_INVALID',
  LEAD_ALREADY_CONVERTED: 'LEAD_ALREADY_CONVERTED',

  // Deal
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  DEAL_STAGE_INVALID: 'DEAL_STAGE_INVALID',
  DEAL_CLOSING_LOCKED: 'DEAL_CLOSING_LOCKED',

  // Property
  PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND',
  PROPERTY_STATUS_CONFLICT: 'PROPERTY_STATUS_CONFLICT',
  PROPERTY_ALREADY_SOLD: 'PROPERTY_ALREADY_SOLD',
  PROPERTY_TYPE_INVALID: 'PROPERTY_TYPE_INVALID',
  PROPERTY_ATTRIBUTES_INVALID: 'PROPERTY_ATTRIBUTES_INVALID',

  // Project
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_HAS_PROPERTIES: 'PROJECT_HAS_PROPERTIES',
  PROJECT_SOLD_OUT: 'PROJECT_SOLD_OUT',
  PROJECT_STATUS_INVALID: 'PROJECT_STATUS_INVALID',

  // Commission
  COMMISSION_PLAN_NOT_FOUND: 'COMMISSION_PLAN_NOT_FOUND',
  COMMISSION_PLAN_MISSING: 'COMMISSION_PLAN_MISSING',
  COMMISSION_ALREADY_SETTLED: 'COMMISSION_ALREADY_SETTLED',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];